version: '3'

networks:
  prodnetwork:
    driver: bridge

volumes:
  nexus-data:
  jenkins_home:

services:
  nexus:
    build: ./nexus
    restart: always
    ports:
      - "18081:8081"
    networks:
      - prodnetwork
    volumes:
      - ./nexus/nexus-data:/nexus-data
  jenkins:
    build: ./jenkins
    restart: always
    ports:
      - "18080:8080"
    networks:
      - prodnetwork
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
    depends_on:
      - nexus
      - sonar
    environment:
      - NEXUS_PORT=8081
      - SONAR_PORT=9000
      - SONAR_DB_PORT=5432
  sonardb:
    networks:
      - prodnetwork
    restart: always
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
     - POSTGRES_USER=sonar
     - POSTGRES_PASSWORD=sonar
  sonar:
    image: sonarqube
    restart: always
    ports:
     - "19000:9000"
     - "19092:9092"
    networks:
      - prodnetwork
    depends_on:
      - sonardb
    environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
     - SONARQUBE_JDBC_USERNAME=sonar
     - SONARQUBE_JDBC_PASSWORD=sonar

  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    environment:
      - external_url='http://192.168.240.175:180'
      - nginx['listen_port']=180
    networks:
      - prodnetwork
    ports:
      - "180:180"
      - "20080:80"
      - "10443:443"
      - "10022:22"
    volumes:
      - ./gitlab/opt/gitlab/config:/etc/gitlab
      - ./gitlab/opt/gitlab/logs:/var/log/gitlab
      - ./gitlab/opt/gitlab/data:/var/opt/gitlab
